### ISSUE TITLE
Can 3D labels be generated?

### ISSUE THREAD

**Issue by yancx8** [flymin/MagicDrive3D#1]
Thank you for your work!
I wonder if 3D labels be generated? Like 3D bbox，extrinsic matrix and intrinsic matrix?

**Comment by flymin** [comment]
No, like [MagicDrive](https://github.com/cure-lab/MagicDrive), 3D labels are inputs, which are used as the conditions for generation. Extrinsic and intrinsic are also inputs for rendering.
