### ISSUE TITLE
What is the Video generator model?

### ISSUE THREAD

**Issue by soohyoen** [flymin/MagicDrive3D#4]
Hello, your work is truly impressive.

However, I’d like to know which model you used for video generation. 

I read your paper, but I wasn’t able to find that information.

**Comment by flymin** [comment]
Hi, as said in the last paragraph in Sec. 1 of our paper, we train the video generation model ourselves. Training details can be found in the last paragraph in Sec. 5.1.

**Comment by soohyoen** [comment]
You're learning with the new video generation model you suggested, not the existing video generator model, right?

**Comment by flymin** [comment]
Yes, we train a new video generation model.

**Comment by soohyoen** [comment]
It`s very awesome for me.

I hope your work will be accepted as soon as possible.
